---
title: "V4: Web search engines"
author: "Patrice Kiener"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{V4: Web search engines}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



## Introduction

**RWsearch** stands for « Search in R packages, task views, CRAN and in the Web ». 

**RWsearch** is a management tool that serves several purposes:

1. Provide a simple instruction to read and evaluate non-standard content (**non-standard evaluation**).
2. Download the **list of all packages** and **task views** available on CRAN at a given date and rearrange them in a convenient format.
3. List the packages that has been added, updated and removed between two dates. 
4. **Search packages that match one or several keywords** (with mode _or_, _and_, _relax_) in any column of the data.frame and by default in columns Package name, Title, Description, Author and Maintainer (can be selected individually).
5. Arrange the results in different format (list, tables with different columns) and display them in console or in txt, md, html, pdf files.
6. In one instruction, download on your disk the whole documentation related to one or several packages. This is the perfect tool to read the documentation off-line. 
7. Provide **tools for task view maintenance**: Detect the packages recently added to or updated in CRAN, check if they match some keywords, check if they are already recorded in a given task views.
8. Provide **quick links to launch web search engines** and search for keywords from the R console. This list of web search engines is expected to grow (with your help).

Compare to other packages ([packagefinder](https://CRAN.R-project.org/package=packagefinder), [websearchr](https://CRAN.R-project.org/package=websearchr)) or web services ([RDocumentation](https://www.rdocumentation.org/search?q=search&latest=1), [rdrr](https://rdrr.io/search?q=search)) with similar objectives, the search options of _RWsearch_ are more sophisticated and allow for a finer search. RWsearch also addresses a much larger number of web search engines. Non-standard evaluation (or evaluation of non-standard content) makes it user friendly.

This vignette deals with point 8. Points 1 to 7 are discussed in other vignettes. 



## Explore the web

Web search engines are major tools to explore the web. Some search engines explores the full web when some other search engines are restricted to a specific website. To remember their favorite search engines, people record them as quick links in their browser. Why not store them directly in an R package and hide in the R functions the specific syntax of each search engine? This is the **W** of **RWsearch**.

This version of **RWsearch** has aleady referred more then 60 web search engines. We expect this number to grow thanks to the contribution of everyone. 





### The generic function 

| Function | Comment |
|----------|---------|
| h_ttp()  | The generic function |
                


### R related links 

|      Function       |  Comment  |
|---------------------|-----------|
| h_R()               | R-project |
| h_cran(repos)       | CRAN |
| h_cranbydate(repos) | CRAN by date |
| h_cranbyname(repos) | CRAN by name  |
| h_crantv(repos)     | CRAN task views
| h_cranberries()     | Cranberries Dirk Eddelbuettel |
| h_gepuro()          | R packages on GitHub |
| h_rbloggers()       | R-bloggers |
| h_rdoc()            | RDocumentation packages  |
| h_rdoctv()          | RDocumentation task views  |
| h_rdrr()            | Rdrr.io  |
| h_rseek()           | Rseek  |


### Direct links

|    Function    | Comment |
|----------------|---------|
| h_academie()   | Académie française's dictionary |
| h_framasoft()  | Framasoft web services |
| h_framasoft0() | Framasoft main page |
| h_lexilogos()  | Hundreds of dictionaries |
| h_linguee()    | Multilingual translation engine |
| h_reverso()    | 13 x 12 translation engines |
| h_tad()        | Time and Date: Create event |
| h_tadsm()      | Time and Date |
| h_yacy()       | Decentralized web search software |

 
### Links with keywords and options

wse: web search engines

|    Function    | Comment |
|----------------|---------|
| h_1bis()       | European maps |
| h_abcbourse()  | stock markets France + EU |
| h_arxiv()      | arXiv  |
| h_arxivpdf()   | arXiv (pdf)  |
| h_ask()        | wse  |
| h_baidu()      | wse China  |
| h_blackle()    | wse in reverse colours  |
| h_bing()       | wse  |
| h_bmap()       | world maps Bing |
| h_boursorama() | stock markets French + EU  |
| h_cnrtl()      | dictionary France |
| h_crossref()   | academic: publication metadata  |
| h_daum()       | wse Korea  |
| h_dm()         | video Daily Motion  |
| h_ddg()        | wse Duck Duck Go  |
| h_ecosia()     | wse + wood + forestry |
| h_egerin()     | wse Kurdish language  |
| h_estrep()     | journal Est Républicain  |
| h_evene()      | French citations in Evene  |
| h_exalead()    | wse  |
| h_excite()     | wse  |
| h_framabee()   | wse France  |
| h_gigablast()  | wse   |
| h_github()     | Github  |
| h_gitlab()     | Gitlab  |
| h_gmap()       | world maps Google  |
| h_google()     | wse  |
| h_gscholar()   | academic  |
| h_ixquick()    | wse see startpage  |
| h_khoj()       | wse Iran  |
| h_lesechos()   | journal Les Échos |
| h_lilo()       | wse   |
| h_lt()         | journal La Tribune  |
| h_lycos()      | wse  |
| h_mappy()      | world maps + yellow pages  |
| h_mw()         | dictionary Merriam-Webster  |
| h_nabble()     | wse  |
| h_nate()       | wse Korea see Daum |
| h_naver()      | wse Korea |
| h_osm()        | world maps Open Street Maps  |
| h_osmn()       | world maps OSM Nominatim  |
| h_parsijoo()   | wse Iran  |
| h_peertube()   | video Peertube  |
| h_peru()       | wse Peru  |
| h_pipilika()   | wse Bengladesh  |
| h_qwant()      | wse   |
| h_qwfr()       | wse France  |
| h_reverso_d()  | dictionaries 13 languages |
| h_sapo()       | wse Portugal  |
| h_searx()      | wse  |
| h_so()         | Stack Overflow  |
| h_sogou()      | wse China   |
| h_ssrn()       | SSRN  |
| h_ssrnauth()   | SSRN (author)  |
| h_startpage()  | wse |
| h_twfr()       | Twitter France  |
| h_twitter()    | Twitter  |
| h_un()         | journal L'Usine Nouvelle  |
| h_verbes()     | dictionary France  |
| h_via()        | world maps Via Michelin  |
| h_vimeo()      | video Vimeo |
| h_wego()       | world maps Wego Here  |
| h_wp()         | Wikipedia  |
| h_wpfr()       | Wikipedia French  |
| h_yahoo()      | wse  |
| h_yandex()     | wse  |
| h_yooz()       | wse Iran |
| h_yt()         | video Youtube  |



## Suggest new search engines

We wish this number to grow thanks to the contribution of everyone. Feel free to suggest me some new links.




